const Score = [
    "Forest",
    "Oscar sets word to “rainforest” and use bongos",
    "Every other person comes in with “rainforest” one at a time",
    "Micah - Frog",
    "Megan - Toucan",
    "Aiden - Orangutan",
    "Alex - Tiger",
    "Until the ending, switch words and sounds",
    "For the ending, each person stops one at a time until it’s just Paul",
    "Alex",
    "Aiden",
    "Megan",
    "Micah",
    "Oscar",
    "Bakery",
    "Oscar starts with “bakery” on drums",
    "Everyone else comes in with “bakery” on salt shaker and paper flip",
    "Micah",
    "Megan",
    "Aiden",
    "Alex",
    "Switch words",
    "Megan and Alex switch to timer",
    "Megan and Alex adjust pitch",
    "Megan get ready for ending",
    "Everyone else, stop on 3",
    "Megan do ending",
    "Block",
    "Starting on the word minecraft using harp (dit) and pling (dah) sound:",
    "Oscar - C C",
    "Micah - G A",
    "Clyde - D E",
    "Start on two different words",
    "Alex - F# A#, cave1 for both. Creeper",
    "Aiden - F# A#, stone2 and gravel1. Zombie",
    "Micah and Clyde leave",
    "Change words",
    "Micah - G G#, change pling to cave. Villager",
    "Clyde - D D#, change pling to pop. Pickaxe",
    "Change to other sounds and words as you please",
    "Use pitches C D E F# G A A# C",
    "Megan get ready for ending",
    "Everyone else, stop on 3",
];


export { Score };