const Score = [
    "Forest",
    "Paul sets word to “rainforest” and use bongos",
    "Every other person comes in with “rainforest” one at a time",
    "Berry - Frog",
    "Clyde - Toucan",
    "Alpha - Orangutan",
    "Sigma - Tiger",
    "Until the ending, switch words and sounds",
    "For the ending, each person stops one at a time until it’s just Paul",
    "Alpha",
    "Sigma",
    "Clyde",
    "Berry",
    "Paul",
    "Bakery",
    "Paul starts with “bakery” on drums",
    "Everyone else comes in with “bakery” on salt shaker and paper flip",
    "Switch words",
    "Eggs, milk, sugar, butter, flour",
    "Clyde and Sigma switch to timer",
    "Clyde and Sigma adjust pitch",
    "Loop off, sustain on - end with just Clyde on timer on lots of dits and a dah (Letters: eeet)",
    "Block",
    "Starting on the word minecraft using harp (dit) and pling (dah) sound:",
    "Oscar - C C",
    "Micah - G A",
    "Clyde - D E",
    "Start on two different words",
    "Micah and Clyde leave",
    "Alex - F# A#, cave1 for both. Creeper",
    "Aiden - F# A#, stone2 and gravel1. Zombie",
    "Change words",
    "Micah - G G#, change pling to cave. Villager",
    "Clyde - D D#, change pling to pop. Pickaxe",
    "Change to other sounds and words as you please",
    "Use pitches C D E F# G A A# C",
    "End with everyone creeper hissing, Going out one by one until its just oscar",
    "Turn off loop button",
    "Oscar plays explosion on e",
    "Then Alex plays villager noise on t to End it (check loop off)"
];


export { Score };